sudo: true
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - clang

before_install:
- chmod +x setup-travis.sh
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.9
- export CXX="g++-4.9"
- ./setup-travis.sh

before_script: chmod +x BuildLinux.sh
script: ./BuildLinux.sh
